package org.apache.whirr.integration.spring;

import org.apache.commons.configuration.ConfigurationException;
import org.apache.commons.configuration.PropertiesConfiguration;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.springframework.beans.factory.FactoryBean;

import java.io.File;

/**
 * Returns a Hadoop {@link Configuration} object based on configuration generated by Whirr.
 */
public class WhirrGeneratedHadoopConfigurationFactoryBean implements FactoryBean<Configuration> {

    private String whirrConfigFile;

    public WhirrGeneratedHadoopConfigurationFactoryBean(String whirrConfigFile) throws ConfigurationException {
        if (!new File(whirrConfigFile).exists()) {
            throw new RuntimeException("No Whirr properties file found at: " + whirrConfigFile);
        }

        this.whirrConfigFile = whirrConfigFile;

        // TODO: Log - found whirr config file

    }

    public Configuration getObject() throws Exception {
        PropertiesConfiguration props = new PropertiesConfiguration(whirrConfigFile);
        String clusterName = props.getString("whirr.cluster-name");

        Configuration configuration = new Configuration();
        configuration.addResource(new Path(System.getProperty("user.home"), ".whirr/" + clusterName + "/" + "hadoop-site.xml"));

        return configuration;
    }

    public Class<?> getObjectType() {
        return Configuration.class;
    }

    public boolean isSingleton() {
        return false;
    }
}